server {
    listen 80;
    server_name localhost;
    root /var/www/html/src/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass web:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_param HTTP_ACCEPT_CHARSET "utf-8";
        fastcgi_param CONTENT_TYPE "text/html; charset=utf-8";
    }

    location ~ /\.ht {
        deny all;
    }

    location ~* \.(woff|woff2|ttf|eot)$ {
            add_header Access-Control-Allow-Origin *;
            types {
                font/woff2 woff2;
                font/woff woff;
                font/ttf ttf;
                application/vnd.ms-fontobject eot;
            }
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
}